openapi: 3.0.0
info:
  version: 1.0.0
  title: Calendar API
  description: A calendar service API specification

servers:
  - url: http://127.0.0.1:8080/api/v1

paths:
  /calendar:
    get:
      description: Hello World            
      responses:
        '200':
          description: Successful response
          content:
            'plain/text':
              schema:
                type: string

  /calendar/event/create:
    post:
      operationId: createEvent
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/EventTemplate'
      responses:
        '200':
          description: OK
          content:
            'plain/text':
              schema:
                type: string

components:
  schemas:
    EventsTemplate:
      type: object
      required:
        - events
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/EventTemplate'

    EventTemplate:
      type: object
      required:
        - id
        - title
        - datetimestart
        - duration
        - alarmtime
      properties:
        id:
          type: string
        title:
          type: string
        datetimestart:
          type: string
        duration:
          type: string
        alarmtime:
          type: string

  securitySchemes:
    UserAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: x-user-id  # name of the header, query parameter or cookie

security:
  - UserAuth: [] 