[logger]
level = "DEBUG"

[db]
type = "sql"
"dsn" = "postgres://hwuser:hwpasswd@0.0.0.0:5432/calendar?sslmode=disable"

[scheduler]
timeoutquery = "10s"
ttldays = "365"

[broker]
dialstring = "amqp://guest:guest@localhost:5672/"
